# Generated by Django 5.0 on 2023-12-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=25)),
                ('bookDesc', models.CharField(max_length=50)),
                ('bookImagePath', models.CharField(max_length=250)),
                ('bookPrice', models.IntegerField()),
                ('bookAuthorName', models.CharField(max_length=25)),
                ('bookPublisherName', models.CharField(max_length=50)),
                ('bookReleaseDate', models.DateTimeField()),
                ('isRentable', models.BooleanField()),
                ('isAvailable', models.BooleanField()),
            ],
        ),
    ]
