# Generated by Django 4.2.7 on 2023-12-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todosAPI", "0002_alter_books_bookimagepath"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="id",
        ),
        migrations.AddField(
            model_name="books",
            name="bookID",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
