# Generated by Django 4.2.7 on 2023-12-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todosAPI", "0003_remove_books_id_books_bookid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="bookID",
        ),
        migrations.AddField(
            model_name="books",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
