# Generated by Django 4.2.7 on 2023-12-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todosAPI", "0004_remove_books_bookid_books_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="bookDesc",
            field=models.CharField(max_length=250),
        ),
    ]
